/* Catálogo Implementos — datos de producto
   Extraídos del catálogo original (Miguel Ángel Cruz Crispin · Mercedes Benz 815) */

window.CATALOG = {
  client: {
    name: "Miguel Ángel Cruz Crispin",
    vehicle: "Mercedes Benz 815",
    code: "GKBD74",
  },

  categories: [
    {
      id: "aceite",
      page: "01",
      name: "Filtros de Aceite",
      short: "Aceite",
      kicker: "Lubricación",
      blurb: "Retención de partículas y protección del motor en cada ciclo de aceite.",
      products: [
        {
          brand: "Donaldson",
          sku: "PACFIL0155",
          flags: ["Original"],
          title: "Filtro Aceite Motor Donaldson P550768",
          subtitle: "Filtro tipo Cartucho",
          specs: [
            ["Aplicación", "Aceite"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "81 mm"],
            ["Ø Interior", "41 mm"],
          ],
          price: 7690,
        },
        {
          brand: "Tecfil",
          sku: "TECFIL0019",
          title: "Filtro Aceite Motor Tecfil PEL2003",
          subtitle: "Filtro tipo Cartucho",
          specs: [
            ["Aplicación", "Aceite"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "81 mm"],
            ["Ø Interior", "41 mm"],
          ],
          price: 3490,
        },
        {
          brand: "Fleetguard",
          sku: "FLGFIL0294",
          title: "Filtro Aceite Motor Fleetguard LF3827",
          subtitle: "Modelos 712 · 912 · 915 / Motor OM904LA",
          specs: [
            ["Aplicación", "Aceite"],
            ["Elemento filtrante", "Celulosa"],
            ["Eficiencia", "88,7 %"],
            ["Ø Exterior", "84 mm"],
            ["Ø Interior", "27 mm"],
          ],
          price: 6990,
        },
      ],
    },

    {
      id: "secadores",
      page: "02",
      name: "Secadores y Separadores",
      short: "Secadores",
      kicker: "Aire comprimido",
      blurb: "Aire seco y limpio para el sistema neumático de frenos y suspensión.",
      products: [
        {
          brand: "Fleetguard",
          sku: "FLGFIL0411",
          imgs: 1,
          title: "AD27750 / AF27817 — Filtro Secador de Aire",
          subtitle: "DAF · Freightliner · International · Iveco · Kenworth · MAN · Mack · Mercedes-Benz · Peterbilt · RVI · Volvo",
          specs: [
            ["Aplicación", "Aire"],
            ["Eficiencia", "0,99"],
            ["Ø Exterior", "140 mm"],
            ["Ø Interior", "130 mm"],
          ],
          price: 32990,
        },
        {
          brand: "Tecfil",
          sku: "TECFIL004",
          title: "Filtro Secador de Frenos Tecfil DSF0204",
          subtitle: "Secador de Aire de Línea de Frenos DSF0204",
          specs: [
            ["Tipo de filtro", "Secundario"],
            ["Aplicación", "Aire de frenos"],
          ],
          price: 23490,
        },
        {
          brand: "Wabco",
          sku: "WABFIL000",
          imgs: 1,
          title: "Filtro Secador de Aire",
          subtitle: "Secador de Aire Silver",
          specs: [
            ["Aplicación", "Aire"],
            ["Hilo", "M39 x 1.5"],
          ],
          price: 32990,
        },
      ],
    },

    {
      id: "aire",
      page: "03",
      name: "Filtros de Aire",
      short: "Aire",
      kicker: "Admisión",
      blurb: "Máxima superficie filtrante para proteger la admisión en ruta y faena.",
      products: [
        {
          brand: "Donaldson",
          sku: "PACFIL0147",
          imgs: 4,
          flags: ["Original"],
          title: "Filtro de Aire Donaldson P781485",
          subtitle: "Filtro Primario",
          specs: [
            ["Aplicación", "Aire"],
            ["Elemento filtrante", "Celulosa"],
            ["Eficiencia", "0,99"],
            ["Ø Exterior", "282 mm"],
            ["Ø Interior", "120 mm"],
          ],
          price: 77990,
          listPrice: 99990,
        },
        {
          brand: "Tecfil",
          sku: "TECFIL0091",
          title: "Filtro de Aire Tecfil ARS9841",
          subtitle: "Filtro de Aire Primario",
          specs: [
            ["Aplicación", "Aire"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "270 mm"],
            ["Ø Interior", "130 mm"],
          ],
          price: 40990,
        },
      ],
    },

    {
      id: "hidraulicos",
      page: "04",
      name: "Filtros Hidráulicos",
      short: "Hidráulicos",
      kicker: "Sistema hidráulico",
      blurb: "Cartuchos de respuesto para dirección y mandos hidráulicos.",
      products: [
        {
          brand: "Agrale",
          sku: "AGRDIR0014",
          title: "Filtro Hidráulico HF6162",
          subtitle: "Filtro Hidráulico tipo Cartucho",
          specs: [
            ["Aplicación", "Hidráulico"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "60 mm"],
            ["Ø Interior", "18 mm"],
          ],
          price: 5990,
        },
        {
          brand: "Fleetguard",
          sku: "FLGFIL0308",
          title: "Filtro Hidráulico Fleetguard HF6162",
          subtitle: "Filtro Hidráulico tipo Cartucho",
          specs: [
            ["Aplicación", "Hidráulico"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "60 mm"],
            ["Ø Interior", "18 mm"],
          ],
          price: 5290,
        },
        {
          brand: "Donaldson",
          sku: "PACFIL0215",
          title: "Filtro Hidráulico Donaldson P550309",
          subtitle: "Filtro Hidráulico tipo Cartucho",
          specs: [
            ["Aplicación", "Hidráulico"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "60 mm"],
            ["Ø Interior", "18 mm"],
          ],
          price: 3990,
        },
        {
          brand: "Tecfil",
          sku: "TECFIL0020",
          flags: ["Cyber", "Oferta"],
          title: "Filtro Hidráulico Tecfil PH346",
          subtitle: "Filtro Hidráulico tipo Cartucho",
          specs: [
            ["Aplicación", "Hidráulico"],
            ["Elemento filtrante", "Celulosa"],
            ["Ø Exterior", "60 mm"],
            ["Ø Interior", "18 mm"],
          ],
          price: 1790,
          listPrice: 2990,
        },
      ],
    },

    {
      id: "frenos",
      page: "09",
      name: "Frenos",
      short: "Frenos",
      kicker: "Seguridad activa",
      blurb: "Pastillas de freno para Mercedes Benz LO916 — desempeño y durabilidad.",
      products: [
        {
          brand: "Fras-le",
          sku: "FRAFRENO245",
          title: "Pastilla Freno Del./tras. Mercedes Benz LO916",
          subtitle: "Heavy Duty",
          specs: [
            ["Composición por juego", "4 piezas"],
            ["Espesor pastilla", "34 mm · 1,3\""],
          ],
          price: 72990,
          bulkPrice: 68990,
          bulkFrom: 10,
        },
        {
          brand: "Fras-le",
          sku: "FRAFRENO246",
          title: "Pastilla Freno Del./tras. Mercedes Benz LO916",
          subtitle: "Advanced",
          specs: [
            ["Composición por juego", "4 piezas"],
            ["Espesor pastilla", "34 mm · 1,3\""],
          ],
          price: 66590,
          bulkPrice: 64990,
          bulkFrom: 10,
        },
        {
          brand: "Suntech",
          sku: "SUNPAS1002",
          flags: ["Cyber"],
          title: "Pastilla Freno Del./tras. Mercedes Benz LO916",
          subtitle: "Pastilla de freno delantera/trasera de origen Brasil. Compuesto cerámico de alto coeficiente de fricción para uso severo en ruta y faena.",
          specs: [
            ["Aplicación", "Mercedes Benz LO916"],
            ["Composición por juego", "4 piezas"],
          ],
          price: 52990,
          listPrice: 64990,
          bulkPrice: 47990,
          bulkFrom: 10,
        },
      ],
    },

    {
      id: "refrigeracion",
      page: "11",
      name: "Refrigeración",
      short: "Refrigeración",
      kicker: "Sistema de enfriamiento",
      blurb: "Componentes para mantener la temperatura óptima del motor en faena pesada.",
      products: [
        {
          brand: "Behr",
          sku: "BEHRAD0021",
          imgs: 3,
          flags: ["Original", "Nuevo"],
          title: "Radiador de Agua Mercedes Benz LO916 — Motor OM904LA",
          subtitle: "Radiador de agua de alto rendimiento para motor OM904LA. Núcleo de aluminio soldado con mayor disipación térmica y resistencia a la corrosión, diseñado para faena pesada y altas temperaturas sostenidas en ruta.",
          specs: [
            ["Aplicación", "Refrigeración"],
            ["Material núcleo", "Aluminio"],
            ["N° de filas", "2"],
            ["Entrada / Salida", "50 mm"],
            ["Alto × Ancho", "680 × 540 mm"],
          ],
          price: 289990,
          listPrice: 349990,
        },
      ],
    },

    {
      id: "lubricantes",
      page: "12",
      name: "Lubricantes",
      short: "Lubricantes",
      kicker: "Aceites y fluidos",
      blurb: "Aceites de motor y fluidos para transmisión y dirección.",
      products: [
        {
          brand: "Lubrax",
          sku: "LBXACE0500",
          imgs: 3,
          flags: ["Cyber", "Oferta"],
          title: "Aceite Motor 15W-40 Mineral — Balde 20 L",
          subtitle: "Aceite mineral multigrado para motores diésel de alto kilometraje. Protección antidesgaste y control de hollín.",
          specs: [
            ["Viscosidad", "15W-40"],
            ["Tipo", "Mineral"],
            ["Norma API", "CI-4"],
            ["Contenido", "20 L"],
          ],
          price: 79990,
          listPrice: 99990,
          bulkPrice: 74990,
          bulkFrom: 4,
        },
        {
          brand: "Lubrax",
          sku: "LBXHID0010",
          imgs: 2,
          title: "Fluido Hidráulico ATF — Bidón 5 L",
          subtitle: "Fluido para transmisiones automáticas y sistemas de dirección hidráulica.",
          specs: [
            ["Tipo", "ATF Dexron III"],
            ["Contenido", "5 L"],
          ],
          price: 24990,
        },
      ],
    },

    {
      id: "electrico",
      page: "13",
      name: "Sistema Eléctrico",
      short: "Eléctrico",
      kicker: "Energía y arranque",
      blurb: "Baterías, alternadores y componentes para el sistema eléctrico del vehículo.",
      products: [
        {
          brand: "Bosch",
          sku: "BSHBAT0150",
          imgs: 4,
          flags: ["Original"],
          title: "Batería 150 Ah — Borne Estándar",
          subtitle: "Batería de alta capacidad para camiones, libre de mantención.",
          specs: [
            ["Capacidad", "150 Ah"],
            ["Voltaje", "12 V"],
            ["CCA", "1000 A"],
            ["Borne", "Estándar"],
          ],
          price: 189990,
          listPrice: 219990,
        },
        {
          brand: "Bosch",
          sku: "BSHBAT0100",
          imgs: 2,
          title: "Batería 100 Ah — Libre Mantención",
          subtitle: "Batería sellada para buses y camiones medianos.",
          specs: [
            ["Capacidad", "100 Ah"],
            ["Voltaje", "12 V"],
            ["CCA", "760 A"],
          ],
          price: 129990,
          bulkPrice: 119990,
          bulkFrom: 4,
        },
        {
          brand: "Valeo",
          sku: "VLOALT0024",
          imgs: 3,
          flags: ["Nuevo"],
          title: "Alternador 24V 80A",
          subtitle: "Alternador de repuesto para línea pesada, 24V.",
          specs: [
            ["Voltaje", "24 V"],
            ["Amperaje", "80 A"],
            ["Polea", "Canal V"],
          ],
          price: 159990,
        },
        {
          brand: "Bosch",
          sku: "BSHMOT0048",
          imgs: 1,
          title: "Motor de Arranque 24V",
          subtitle: "Motor de partida reforzado para motor OM904LA.",
          specs: [
            ["Voltaje", "24 V"],
            ["Potencia", "4 kW"],
            ["Dientes piñón", "10"],
          ],
          price: 219990,
          listPrice: 259990,
        },
      ],
    },

    {
      id: "correas",
      page: "14",
      name: "Correas y Tensores",
      short: "Correas",
      kicker: "Transmisión accesoria",
      blurb: "Correas multicanal y tensores para el accionamiento de accesorios del motor.",
      products: [
        {
          brand: "Gates",
          sku: "GTSCOR8PK",
          imgs: 1,
          flags: ["Original"],
          title: "Correa Multicanal 8PK 1815 — Micro-V",
          subtitle: "Correa Micro-V de 8 canales para accionamiento de accesorios. Compuesto EPDM de larga duración, resistente a altas temperaturas y al agrietamiento, para motor OM904LA y similares.",
          specs: [
            ["Tipo", "Micro-V 8PK"],
            ["Largo", "1815 mm"],
            ["N° de canales", "8"],
            ["Material", "EPDM"],
          ],
          price: 34990,
          listPrice: 41990,
        },
      ],
    },
  ],
};
